### ISSUE TITLE
Comments on training notebooks

### ISSUE THREAD

**Issue by AnderBiguri** [gschramm/pyapetnet#1]
Hi!

Just to be clear, the notebooks are awesome, definitely really good, so this is more of a nitpick than a serious criticism, so feel free to ignore it. 

- `01_tf_data.ipynb`
    The reason of these data indices is not clear in the code/test, may be confusing?
    `x[3*i + sim,...,0] = data[0][40:-40,30:-30,40:-40]`

    The exercise says "Modify `train_data`" but there is no such function/variable as `train_data`.

- `02_tf_models.ipynb`
    You will inevitably get the question "why MSE, why Adam, why 1e-3". One option is to write something in the notebook (albeit I know the answer is probably "we tried it and it works"), the other is just to be ready for the question :).
    
    The section that does `# generate artificial training and validation data` may use some code-comments, but admittedly, with a quick look I can infer what everything is doing. Maybe its good as is, so people scratch their head a bit.

That's all! 
Let me repeat that this notebooks are awesome. I can only be described as someone with a mild interest on NN that only programmed a fully contented perception network 10 years ago and I could follow this tutorial (with some google searches) quite well.

**Comment by gschramm** [comment]
Thanks for all the feedback! I included all your comments and also added the automatic data download in the 00_*.ipynb notebook since the data is now available on Zenodo.

Could you run a final test of all notebooks including the data download?

**Comment by AnderBiguri** [comment]
Sorry been super busy doing tons of computing on my machine and I had no time to test. Hopefully I will in the next days!
