### ISSUE TITLE
pyapetnet issue

### ISSUE THREAD

**Issue by AFPET** [gschramm/pyapetnet#3]
Hello:
pyapetnet installation seems to be complete, but I do not get as the installation instructions says "number of command line scripts all starting with pyapetnet* "  
Instead, I get the following with no further actions.

{
(pyapetnet) PS C:\Users\User> python
Python 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyapetnet
>>> print(pyapetnet.__version__)
1.1.1
>>> print(pyapetnet.__file__)
C:\Users\User\miniconda3\envs\pyapetnet\lib\site-packages\pyapetnet\__init__.py
>>>
}

any idea what is the issue?
thanks

**Comment by gschramm** [comment]
Hi Adam,

1. The test within python seem fine. They show that you have installed the python package pyapetnet v.1.1.1 in your pyapetnet miniconda environment.
2. The installation of pyapetnet comes with 3 command line tools that you can use to make predictions with pre-trained models in pyapetnet. 
   1. ```pyapetnet_list_models```
   2. ```pyapetnet_predict_from_nifti```
   3. ```pyapetnet_predict_from_dicom```

You can run all of them directly from the command line without starting python (but you must have activate your conda environment). If you run them with ```-h``` you can see the help page of all scripts.

If you want to understand what is going on under the hood when doing predictions, you can run [this notebook](https://github.com/gschramm/pyapetnet/blob/master/notebooks/04_inference_demo_brainweb.ipynb).

If you want to train your own models, you can have a look at [this script](https://github.com/gschramm/pyapetnet/blob/master/scripts_bow/train_bow_cnn_tf2.py).

**Comment by AFPET** [comment]
Thank you for the reply, I still cannot get the package working. I use the conda powershell (py3k) to run the pretrained models you listed above and I get the error:
{ pyapetnet_predict_from_nifti : The term 'pyapetnet_predict_from_nifti' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.}
Not sure what I am doing wrong.

**Comment by gschramm** [comment]
sorry to hear that. Did you activate the virtual conda env where you install pyapetnet?

To test this you could e.g. execute:
```
python -c "import pyapetnet; print(pyapetnet.__file__)"
```

If this gives an error pyapetnet is not correctly installed.

**Comment by AFPET** [comment]
Hi Georg,

 

Attached is a screenshot of correct installation confirmation showing the _init_.py in the directory.

Also I attach the errors I get when I start with command  “pyapetnet_predict_from_nifti osem.nii t1.nii S2_osem_b10_fdg_pe2i –show”.

It seems looking for library and other associated files and can not find them.

 

On another note what is the purpose of the package I downloaded if I am not pointing or using it for installation?

I appreciate your patient and help in this, I really hope to get this working this week.

 

Best

Adam

**Comment by AFPET** [comment]
all good thx.

**Comment by gschramm** [comment]
Good to hear that. What was the issue?
